[manager]
cwd = {fg =  "#959FA9"}
hovered = {fg = "#798692" }
preview_hovered = {fg =  "#798692"}
marker_selected = {fg =  "#959FA9"}
marker_copied = {fg =  "#959FA9"}
border_style = {fg =  "#959FA9"} 
tab_active = {fg =  "#959FA9"}
tab_inactive = {fg =  "#959FA9"}
tab_width = 5
[select]
inactive = {fg = "#58688c"}
active = {fg = "#ffffff", bg = "#264662"}
selected  = {fg = "#ffffff"}
value  = {fg = "#ffffff"}


[input]
title = {fg =  "#ffffff"} 

[completion]
active = {fg = "#264662"}
inactive = {fg = "#264662"}
icon_folder = "🗀" 

[tasks]
title  = {fg = "#ffffff"}

[status]
mode_normal  = {fg =  "#1a1417"}
mode_select = {fg =  "#1a1417"} 

[help]
run  = {fg = "#264662"}
on  = {fg = "#264662"}
desc  = {fg = "#264662"}
hovered  = {fg = "#264662"}
footer  = {fg = "#264662"}













[theme]
name = "MyCustomTheme"

# Define the styles for different file types
[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "#959FA9" },

    # Videos
    { mime = "video/*", fg =  "#959FA9"  },
    { mime = "audio/*", fg =  "#959FA9"  },

    # Empty files
    { mime = "inode/x-empty", fg =  "#959FA9"  },

    # Orphan symbolic links
    { name = "*", is = "orphan", fg = "#959FA9" },

    # All files
    { name = "*", fg = "#959FA9" },

    # All directories
    { name = "*/", fg = "#959FA9", text = "🗀"  }
]

# Set the icon color

